name: storybook
description: ArDrive Design System Storybook

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ardrive_ui:
    path: ../
  widgetbook: 3.0.0-beta.14
  intl: ^0.17.0
  collection: ^1.16.0

dependency_overrides:
  widgetbook_core: 3.0.0-beta.8
  file_picker:
    git:
      url: https://github.com/ar-io/flutter_file_picker
      ref: a4902ec620ba28c484bf84a0cea4669f3d3698fe

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
