on:
  workflow_call:
    inputs:
      FIREBASE_TARGET:
        required: true
        type: string
      FIREBASE_EXPIRES:
        type: string
      FIREBASE_CHANNEL:
        type: string

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set Flutter version from fvm
      - uses: kuhnroyal/flutter-fvm-config-action@v1

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build storybook
        working-directory: ./storybook
        run: |
          flutter clean && flutter pub get
          flutter build web --release

      # Disribute to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_CI_SERVICE_ACCOUNT }}
          target: ${{ inputs.FIREBASE_TARGET }}
          expires: ${{ inputs.FIREBASE_EXPIRES }}
          channelId: ${{ inputs.FIREBASE_CHANNEL }}
