on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set Flutter version from fvm
      - uses: kuhnroyal/flutter-fvm-config-action@v1

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Fetch dependencies
        run: flutter pub get

      - name: Fetch storybook dependencies
        working-directory: ./storybook
        run: flutter pub get

      - name: Lint
        run: flutter analyze

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set Flutter version from fvm
      - uses: kuhnroyal/flutter-fvm-config-action@v1

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Fetch dependencies
        run: flutter pub get

      - name: Fetch storybook dependencies
        working-directory: ./storybook
        run: flutter pub get

      - name: Test
        run: flutter test
